using SkiaSharp;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text.Json;
static class ImageProof {
 public static void Run(){var root=Path.Combine(Program.Root,"fixtures");Directory.CreateDirectory(root);Program.Log("image-vectors",ImageVectors.Run(root));ColorVectors(root);
 var legacy=Path.Combine(Directory.GetCurrentDirectory(),"tools/X3G3Completion/fixtures");foreach(var n in new[]{"tiff-lzw.tiff","tiff-packbits.tiff"})File.Copy(Path.Combine(legacy,n),Path.Combine(root,n),true);
 Program.Log("heic-encoding",new{available=Native.x3_make_heic(Path.Combine(root,"thumb-00.png"),Path.Combine(root,"vector.heic"))==1});
 foreach(var path in Directory.GetFiles(root).Where(p=>!Path.GetFileName(p).StartsWith("thumb-")||Path.GetFileName(p)=="thumb-00.png")){
 using var codec=SKCodec.Create(path);var p=Native.x3_decode_image(path,out int width,out int height,out int orientation);if(p==IntPtr.Zero){Program.Log("image-adapter",new{fixture=Path.GetFileName(path),skia=codec!=null,imageIO=false});continue;}
 try{var metadata=JsonDocument.Parse(Marshal.PtrToStringUTF8(Native.x3_image_info())!);using var cs=SKColorSpace.CreateSrgb();using var pixels=new SKBitmap(new SKImageInfo(width,height,SKColorType.Rgba8888,SKAlphaType.Premul,cs));var bytes=new byte[width*height*4];Marshal.Copy(p,bytes,0,bytes.Length);Marshal.Copy(bytes,0,pixels.GetPixels(),bytes.Length);
 using var normalized=ImageVectors.Orient(pixels,(SKEncodedOrigin)orientation);using var encoded=normalized.Encode(SKEncodedImageFormat.Png,100);using var stream=new MemoryStream(encoded.ToArray());using var ui=new Avalonia.Media.Imaging.Bitmap(stream);CompletionWindow.Check(ui.PixelSize.Width==normalized.Width&&ui.PixelSize.Height==normalized.Height,"normalized image dimensions "+Path.GetFileName(path));
 var c=pixels.GetPixel(0,0);int? maxError=null;if(codec!=null){using var decoded=new SKBitmap(new SKImageInfo(codec.Info.Width,codec.Info.Height,SKColorType.Rgba8888,SKAlphaType.Premul,cs));codec.GetPixels(decoded.Info,decoded.GetPixels());using var oriented=ImageVectors.Orient(decoded,codec.EncodedOrigin);if(oriented.Width==normalized.Width&&oriented.Height==normalized.Height){int error=0;for(int y=0;y<oriented.Height;y++)for(int x=0;x<oriented.Width;x++){var a=oriented.GetPixel(x,y);var b=normalized.GetPixel(x,y);error=Math.Max(error,new[]{Math.Abs(a.Red-b.Red),Math.Abs(a.Green-b.Green),Math.Abs(a.Blue-b.Blue),Math.Abs(a.Alpha-b.Alpha)}.Max());}maxError=error;}}
 if(Path.GetFileName(path)=="linear-profile-alpha.png")CompletionWindow.Check(Math.Abs(c.Red-188)<=1&&c.Alpha==128,"ImageIO linear ICC and alpha match explicit sRGB intent");
 Program.Log("image-adapter",new{fixture=Path.GetFileName(path),skia=codec!=null,imageIO=true,width,height,orientation,normalizedWidth=normalized.Width,normalizedHeight=normalized.Height,rgba=new[]{c.Red,c.Green,c.Blue,c.Alpha},maxError,metadata=metadata.RootElement.Clone(),sourceSha=Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(path))),sourceBytesPreserved=true,copyPolicy="native premul RGBA -> owned shared pixels -> normalized PNG -> Avalonia decode; no zero-copy claim"});
 }finally{Native.x3_free_image(p);}}
 var watch=System.Diagnostics.Stopwatch.StartNew();for(int i=0;i<100;i++){var p=Native.x3_decode_image(Path.Combine(root,"vector.tiff"),out _,out _,out _);CompletionWindow.Check(p!=IntPtr.Zero,"TIFF lifetime decode");Native.x3_free_image(p);}CompletionWindow.Check(Native.x3_image_buffers()==0,"native image resources balanced");Program.Log("image-lifetime",new{decodes=100,buffers=Native.x3_image_buffers(),elapsedMs=watch.Elapsed.TotalMilliseconds});Program.Log("layer-color-adapter",new{before=Marshal.PtrToStringUTF8(Native.x3_layer_color(0)),after=Marshal.PtrToStringUTF8(Native.x3_layer_color(1))});Program.Log("display-profile",new{native=Marshal.PtrToStringUTF8(Native.x3_display()),intent="source profile -> explicit sRGB SDR pixels; platform presentation profile requires explicit tagging; physical calibration deferred"});
 }

 static void ColorVectors(string root){using var linear=SKColorSpace.CreateSrgbLinear();using var srgb=SKColorSpace.CreateSrgb();int n=0;foreach(byte v in new byte[]{0,64,128,192,255})foreach(byte alpha in new byte[]{0,64,128,255}){using var b=new SKBitmap(new SKImageInfo(1,1,SKColorType.Rgba8888,SKAlphaType.Unpremul,linear));Marshal.Copy(new byte[]{v,v,v,alpha},0,b.GetPixels(),4);using var data=b.Encode(SKEncodedImageFormat.Png,100);var path=Path.Combine(root,$"icc-{n++}.png");File.WriteAllBytes(path,data.ToArray());using var codec=SKCodec.Create(path);using var target=new SKBitmap(new SKImageInfo(1,1,SKColorType.Rgba8888,SKAlphaType.Premul,srgb));codec.GetPixels(target.Info,target.GetPixels());var sk=new byte[4];Marshal.Copy(target.GetPixels(),sk,0,4);var p=Native.x3_decode_image(path,out _,out _,out _);var cg=new byte[4];try{Marshal.Copy(p,cg,0,4);}finally{Native.x3_free_image(p);}double x=v/255d;double y=x<=.0031308?12.92*x:1.055*Math.Pow(x,1/2.4)-.055;int expected=(int)Math.Round(y*alpha);bool ok=Math.Abs(sk[0]-expected)<=1&&Math.Abs(cg[0]-expected)<=1&&sk[3]==alpha&&cg[3]==alpha;CompletionWindow.Check(ok,"linear ICC premultiplied vector "+n);Program.Log("icc-vector",new{linear=v,alpha,expected,skia=sk.Select(x=>(int)x).ToArray(),imageIO=cg.Select(x=>(int)x).ToArray(),ok});}}
}
