using Avalonia;
using Avalonia.Automation;
using Avalonia.Automation.Peers;
using Avalonia.Automation.Provider;
using Avalonia.Controls;
using Avalonia.Input;
using Avalonia.Input.Raw;
using Avalonia.Interactivity;
using Avalonia.Layout;
using Avalonia.Native;
using Avalonia.VisualTree;
using Lightflow.Actions;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Text.Json;
using System.Windows.Input;

sealed class ProofCommand(Action execute,Func<bool> enabled):ICommand {public event EventHandler? CanExecuteChanged;public bool CanExecute(object? p)=>enabled();public void Execute(object? p){if(CanExecute(p))execute();}public void Refresh()=>CanExecuteChanged?.Invoke(this,EventArgs.Empty);}
sealed class RawDriver:IDisposable {
 readonly Window w;readonly object root;ulong stamp=100;readonly object keyboard;readonly MouseDevice mouse;
 public RawDriver(Window window){w=window;root=typeof(TopLevel).GetProperty("InputRoot",BindingFlags.Instance|BindingFlags.NonPublic)!.GetValue(w)!;keyboard=typeof(AvaloniaNativePlatformOptions).Assembly.GetType("Avalonia.Native.AvaloniaNativePlatform")!.GetField("KeyboardDevice",BindingFlags.Static|BindingFlags.NonPublic|BindingFlags.Public)!.GetValue(null)!;mouse=(MouseDevice)Activator.CreateInstance(typeof(MouseDevice),BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic,null,new object?[]{null},null)!;}
 T Make<T>(params object[] args){var ctors=typeof(T).GetConstructors(BindingFlags.Instance|BindingFlags.Public|BindingFlags.NonPublic);foreach(var c in ctors){var p=c.GetParameters();if(p.Length<args.Length)continue;var a=new object?[p.Length];bool ok=true;for(int i=0;i<p.Length;i++){if(i<args.Length){a[i]=args[i];if(!p[i].ParameterType.IsInstanceOfType(args[i]))ok=false;}else if(p[i].HasDefaultValue)a[i]=p[i].DefaultValue;else ok=false;}if(ok)return (T)c.Invoke(a);}throw new Exception(typeof(T).Name+" constructors: "+string.Join(";",ctors.Select(c=>c.ToString()))+" args:"+string.Join(",",args.Select(a=>a.GetType().Name)));}
 void Send(RawInputEventArgs e)=>root.GetType().GetMethod("HandleInput",BindingFlags.Instance|BindingFlags.NonPublic)!.Invoke(root,new object[]{e});
 public void Key(Key key,RawInputModifiers mods=RawInputModifiers.None){Send(Make<RawKeyEventArgs>(keyboard,stamp+=100,root,RawKeyEventType.KeyDown,key,mods,PhysicalKey.None,key.ToString(),KeyDeviceType.Keyboard));Send(Make<RawKeyEventArgs>(keyboard,stamp+=100,root,RawKeyEventType.KeyUp,key,mods,PhysicalKey.None,key.ToString(),KeyDeviceType.Keyboard));}
 public void Text(string text)=>Send(Make<RawTextInputEventArgs>(keyboard,stamp+=100,root,text));
 public void Click(Control c,bool right=false,RawInputModifiers mods=RawInputModifiers.None){var p=c.TranslatePoint(new Point(c.Bounds.Width/2,c.Bounds.Height/2),w)!.Value;Send(Make<RawPointerEventArgs>(mouse,stamp+=100,root,RawPointerEventType.Move,p,mods));Send(Make<RawPointerEventArgs>(mouse,stamp+=100,root,right?RawPointerEventType.RightButtonDown:RawPointerEventType.LeftButtonDown,p,mods|(right?RawInputModifiers.RightMouseButton:RawInputModifiers.LeftMouseButton)));Send(Make<RawPointerEventArgs>(mouse,stamp+=100,root,right?RawPointerEventType.RightButtonUp:RawPointerEventType.LeftButtonUp,p,mods));}
 public void Dispose()=>((IDisposable)mouse).Dispose();
}
static class InputProof {
 static KeyboardGesture? Translate(Key key,KeyModifiers m){if(key is Key.LeftCtrl or Key.RightCtrl or Key.LeftShift or Key.RightShift or Key.LeftAlt or Key.RightAlt or Key.LWin or Key.RWin)return null;var text=key==Key.Return?"Enter":key.ToString();var mods=ShortcutModifiers.None;if(m.HasFlag(KeyModifiers.Meta))mods|=ShortcutModifiers.Primary;if(m.HasFlag(KeyModifiers.Control))mods|=ShortcutModifiers.Control;if(m.HasFlag(KeyModifiers.Alt))mods|=ShortcutModifiers.Alt;if(m.HasFlag(KeyModifiers.Shift))mods|=ShortcutModifiers.Shift;return new(text,mods);}
 public static async Task Run(CompletionWindow w){var edit=new Button{Content="Edit Play / Pause shortcut"};var apply=new Button{Content="Use Shortcut",IsEnabled=false};var cancel=new Button{Content="Cancel"};var feedback=new TextBlock{Text="Shortcut unassigned"};var tree=new TreeView{ItemsSource=new[]{new TreeViewItem{Header="Collections",IsExpanded=true,ItemsSource=new[]{new TreeViewItem{Header="Selected takes"}}}}};
 var row=new StackPanel{Spacing=10,Margin=new Thickness(16),Children={new TextBlock{Text="Settings — Keyboard Shortcuts",FontSize=22},edit,feedback,apply,cancel,new TextBlock{Text="Collections / Browser"},tree}};w.Body.Content=row;AutomationProperties.SetName(tree,"Collections navigation");foreach(var t in tree.Items.OfType<TreeViewItem>()){AutomationProperties.SetName(t,t.Header?.ToString());foreach(var child in t.Items.OfType<TreeViewItem>())AutomationProperties.SetName(child,child.Header?.ToString());}
 AutomationProperties.SetName(edit,"Edit Play Pause keyboard shortcut");AutomationProperties.SetName(feedback,"Shortcut capture status");AutomationProperties.SetLiveSetting(feedback,AutomationLiveSetting.Polite);
 var profile=new ShortcutProfile();var play=KeyboardCommandCatalog.Commands.Single(x=>x.Id=="player.play-pause");var other=KeyboardCommandCatalog.Commands.Single(x=>x.Id=="player.color-bypass");profile.Set(play,new KeyboardGesture("Space"),ShortcutPlatform.MacOS);
 bool capturing=false;Key? captureRelease=null;KeyboardGesture? candidate=null;int actions=0;string? error=null;
 void Start(){capturing=true;candidate=null;apply.IsEnabled=false;feedback.Text="Press shortcut; Escape cancels";edit.Focus();}
 void Stop(){capturing=false;candidate=null;apply.IsEnabled=false;edit.Focus();}
 edit.Click+=(_,_)=>Start();cancel.Click+=(_,_)=>Stop();apply.Click+=(_,_)=>{if(candidate!=null)profile.Set(play,candidate,ShortcutPlatform.MacOS);Stop();};
 void Handle(object? s,KeyEventArgs e){if(capturing){if(e.Key==Key.Escape){Stop();e.Handled=true;return;}if(e.Key==Key.Tab){Stop();return;}e.Handled=true;captureRelease=e.Key;var g=Translate(e.Key,e.KeyModifiers);if(g==null)return;error=new KeyboardShortcutResolver(profile,ShortcutPlatform.MacOS).Validate(play,g);candidate=error==null?g:null;feedback.Text=error??g.Display(ShortcutPlatform.MacOS);apply.IsEnabled=candidate!=null;if(candidate!=null)apply.Focus();return;}
 if(w.FocusManager?.GetFocusedElement() is TextBox||w.FocusManager?.GetFocusedElement() is Button)return;
 var gesture=Translate(e.Key,e.KeyModifiers);if(gesture!=null&&new KeyboardShortcutResolver(profile,ShortcutPlatform.MacOS).Resolve(gesture,ShortcutContext.Player)!=null){actions++;e.Handled=true;}}
 void Release(object? s,KeyEventArgs e){if(captureRelease==e.Key){e.Handled=true;captureRelease=null;}}
 w.AddHandler(InputElement.KeyUpEvent,Release,RoutingStrategies.Tunnel);w.AddHandler(InputElement.KeyDownEvent,Handle,RoutingStrategies.Tunnel);await Task.Delay(100);using var raw=new RawDriver(w);
 foreach(var x in new[]{(Key.K,RawInputModifiers.None),(Key.K,RawInputModifiers.Meta),(Key.K,RawInputModifiers.Alt),(Key.K,RawInputModifiers.Control),(Key.K,RawInputModifiers.Shift),(Key.Left,RawInputModifiers.None),(Key.Right,RawInputModifiers.None),(Key.Up,RawInputModifiers.None),(Key.Down,RawInputModifiers.None),(Key.Space,RawInputModifiers.None),(Key.Delete,RawInputModifiers.None),(Key.Back,RawInputModifiers.None)}){Start();int old=actions;raw.Key(x.Item1,x.Item2);CompletionWindow.Check(actions==old,"capture suppresses global "+x);Program.Log("shortcut-capture",new{key=x.Item1.ToString(),mod=x.Item2.ToString(),candidate,error,feedback=feedback.Text,focus=w.FocusManager?.GetFocusedElement()?.GetType().Name});if(x.Item1 is not Key.Delete and not Key.Back)CompletionWindow.Check(candidate!=null,"supported shortcut "+x);else CompletionWindow.Check(candidate==null,"local Delete/Backspace not collapsed into bindable gesture");}
 Start();raw.Key(Key.LeftShift);CompletionWindow.Check(candidate==null&&capturing,"modifier-only ignored");raw.Key(Key.Escape);CompletionWindow.Check(!capturing&&edit.IsFocused,"Escape cancel restores focus");
 profile.Set(other,new KeyboardGesture("K",ShortcutModifiers.Primary),ShortcutPlatform.MacOS);Start();raw.Key(Key.K,RawInputModifiers.Meta);CompletionWindow.Check(error?.StartsWith("Conflicts") == true&&!apply.IsEnabled,"shared resolver conflict");Stop();
 var before=actions;w.Editor.Focus();raw.Key(Key.Space);raw.Text("Z");CompletionWindow.Check(actions==before&&w.Editor.Text!.Contains('Z'),"text owner suppresses globals and accepts text");raw.Key(Key.A,RawInputModifiers.Meta);raw.Text("Edited caption");CompletionWindow.Check(w.Editor.Text=="Edited caption","Command+A remains local text selection");
 var target=new SurfaceControl{Height=80,Focusable=true};AutomationProperties.SetName(target,"Player presentation, paused frame 15");row.Children.Add(target);await Task.Delay(30);target.Focus();raw.Key(Key.Space);CompletionWindow.Check(actions==before+1,"shortcut resumes outside editor");
 int contextEpoch=1,menuActions=0;var captured=contextEpoch;var action=new ProofCommand(()=>menuActions++,()=>captured==contextEpoch);var item=new MenuItem{Header="Inspect selection",Command=action,InputGesture=new KeyGesture(Key.I,KeyModifiers.Meta)};var disabled=new MenuItem{Header="Regenerate previews",IsEnabled=false};var menu=new ContextMenu{ItemsSource=new[]{item,disabled}};target.ContextMenu=menu;
 raw.Click(target,true);await Task.Delay(50);CompletionWindow.Check(menu.IsOpen,"raw right-click opens context menu");await w.Snapshot("context-menu");DumpNative("context-menu");item.RaiseEvent(new RoutedEventArgs(MenuItem.ClickEvent));await Task.Delay(20);CompletionWindow.Check(menuActions==1,"context action independent of incidental focus");menu.Close();captured=contextEpoch;menu.Open(target);contextEpoch++;action.Refresh();await Task.Delay(20);var invocations=menuActions;action.Execute(null);CompletionWindow.Check(menuActions==invocations&&!action.CanExecute(null),"stale menu target disabled and suppressed");menu.Close();
 // Mac control-click adapter maps the chord explicitly; never converts ordinary Ctrl keys into Primary.
 target.PointerPressed+=(_,e)=>{if(e.KeyModifiers.HasFlag(KeyModifiers.Control)&&e.GetCurrentPoint(target).Properties.IsLeftButtonPressed){captured=contextEpoch;action.Refresh();menu.Open(target);e.Handled=true;}};raw.Click(target,false,RawInputModifiers.Control);await Task.Delay(30);CompletionWindow.Check(menu.IsOpen,"Control-click adapter");raw.Key(Key.Escape);await Task.Delay(20);CompletionWindow.Check(!menu.IsOpen,"Escape dismisses context menu");target.Focus();raw.Key(Key.Space);CompletionWindow.Check(actions==before+2,"keyboard restored after menu");
 var native=new NativeMenu();var settings=new NativeMenuItem("Settings…"){Gesture=new KeyGesture(Key.OemComma,KeyModifiers.Meta),Command=new ProofCommand(()=>w.Status.Text="Settings invoked",()=>true)};native.Items.Add(settings);NativeMenu.SetMenu(w,native);w.Activate();string menuJson="";for(int poll=0;poll<30;poll++){await Task.Delay(100);menuJson=Marshal.PtrToStringUTF8(Native.x3_menu())??"";if(menuJson.Contains("Settings"))break;}CompletionWindow.Check(menuJson.Contains("Settings"),"native Settings menu exported after activation");Program.Log("native-menu",new{json=menuJson,shortcut=new KeyboardGesture("K",ShortcutModifiers.Primary).Display(ShortcutPlatform.MacOS),windows=new KeyboardGesture("K",ShortcutModifiers.Primary).Display(ShortcutPlatform.Windows)});
 Start();raw.Key(Key.J);var firstFocus=w.FocusManager?.GetFocusedElement();raw.Key(Key.Tab);Program.Log("focus-order",new{first=firstFocus?.GetType().Name,next=w.FocusManager?.GetFocusedElement()?.GetType().Name,scope="raw Tab in staged capture"});Stop();DetailsProof.DumpPeers(row,"Settings-Player-Collections");DumpNative("settings");await w.Snapshot("settings-shortcuts");Program.Log("input-summary",new{actions,menuActions,conflict=true,staleContext=true,scope="actual Avalonia TopLevel raw input, not OS keyboard translation; production shared resolver unchanged"});w.RemoveHandler(InputElement.KeyDownEvent,Handle);w.RemoveHandler(InputElement.KeyUpEvent,Release);
 }
 public static void DumpNative(string name){var json=Marshal.PtrToStringUTF8(Native.x3_ax())??"[]";System.IO.File.WriteAllText(System.IO.Path.Combine(Program.Root,name+"-native-ax.json"),json);Program.Log("native-ax",new{name,count=JsonDocument.Parse(json).RootElement.GetArrayLength()});}
}
