// Task-only G1b integration harness. No production linkage or Lightflow user data.
#import <AppKit/AppKit.h>
#import <Metal/Metal.h>
#import <QuartzCore/CAMetalLayer.h>
#import <IOSurface/IOSurface.h>
#import <CoreVideo/CoreVideo.h>
#include <AudioToolbox/AudioToolbox.h>
#include <mach/mach.h>
#include <atomic>
#include <vector>
#include <deque>
#include <memory>
#include <algorithm>
#include <chrono>
#include <thread>
extern "C" {
#include <libavformat/avformat.h>
#include <libavcodec/avcodec.h>
#include <libavutil/hwcontext.h>
#include <libavutil/display.h>
#include <libavfilter/avfilter.h>
#include <libavfilter/buffersrc.h>
#include <libavfilter/buffersink.h>
#include <libswscale/swscale.h>
}
static double now(){return std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count();}
static void emit(NSDictionary *r){NSData *d=[NSJSONSerialization dataWithJSONObject:r options:0 error:nil];printf("%s\n",[[[NSString alloc]initWithData:d encoding:NSUTF8StringEncoding]UTF8String]);fflush(stdout);}
static void ck(int n){if(n<0){char b[256];av_strerror(n,b,sizeof(b));fprintf(stderr,"FFmpeg: %s\n",b);exit(2);}}
static void aqck(OSStatus n){if(n){fprintf(stderr,"AudioQueue: %d\n",(int)n);exit(3);}}
static uint64_t hash(const uint8_t *p,size_t n){uint64_t h=14695981039346656037ULL;while(n--){h^=*p++;h*=1099511628211ULL;}return h;}
static NSString *hs(uint64_t h){return [NSString stringWithFormat:@"%016llx",(unsigned long long)h];}
static void pump(double seconds){double end=now()+seconds;do{NSEvent *e=[NSApp nextEventMatchingMask:NSEventMaskAny untilDate:[NSDate dateWithTimeIntervalSinceNow:.001] inMode:NSDefaultRunLoopMode dequeue:YES];if(e)[NSApp sendEvent:e];[NSApp updateWindows];}while(now()<end);}
static uint64_t rss(){mach_task_basic_info_data_t i;mach_msg_type_number_t n=MACH_TASK_BASIC_INFO_COUNT;task_info(mach_task_self(),MACH_TASK_BASIC_INFO,(task_info_t)&i,&n);return i.resident_size;}
struct Decoded { AVFrame *frame;const int64_t pts;const AVRational tb;const uint64_t sequence; Decoded(AVFrame*f,AVRational t,uint64_t s):frame(av_frame_clone(f)),pts(f->pts),tb(t),sequence(s){} ~Decoded(){av_frame_free(&frame);} };
using Frame=std::shared_ptr<const Decoded>;
static AVPixelFormat choose(AVCodecContext*,const AVPixelFormat *f){for(;*f!=AV_PIX_FMT_NONE;f++)if(*f==AV_PIX_FMT_VIDEOTOOLBOX)return *f;return AV_PIX_FMT_NONE;}
class Decoder {
 AVFormatContext *fmt=nullptr;AVCodecContext *dec=nullptr;AVPacket *packet=av_packet_alloc();AVFrame *f=av_frame_alloc();bool drained=false;uint64_t seq=0;
public:int stream;AVRational tb;int w,h,rotation;double duration;uint64_t framesRead=0;
 Decoder(const char *path,bool hw){ck(avformat_open_input(&fmt,path,0,0));ck(avformat_find_stream_info(fmt,0));stream=av_find_best_stream(fmt,AVMEDIA_TYPE_VIDEO,-1,-1,0,0);ck(stream);auto s=fmt->streams[stream];tb=s->time_base;w=s->codecpar->width;h=s->codecpar->height;duration=fmt->duration/(double)AV_TIME_BASE;auto side=av_packet_side_data_get(s->codecpar->coded_side_data,s->codecpar->nb_coded_side_data,AV_PKT_DATA_DISPLAYMATRIX);rotation=side?((int)llround(-av_display_rotation_get((int32_t*)side->data)/90)+4)%4:0;dec=avcodec_alloc_context3(avcodec_find_decoder(s->codecpar->codec_id));ck(avcodec_parameters_to_context(dec,s->codecpar));dec->thread_count=2;if(hw){ck(av_hwdevice_ctx_create(&dec->hw_device_ctx,AV_HWDEVICE_TYPE_VIDEOTOOLBOX,0,0,0));dec->get_format=choose;}ck(avcodec_open2(dec,dec->codec,0));}
 ~Decoder(){av_frame_free(&f);av_packet_free(&packet);avcodec_free_context(&dec);avformat_close_input(&fmt);}
 Frame next(){while(true){int r=avcodec_receive_frame(dec,f);if(r==0){if(f->pts==AV_NOPTS_VALUE)exit(8);framesRead++;auto x=std::make_shared<Decoded>(f,tb,seq++);av_frame_unref(f);return x;}if(r==AVERROR_EOF)return {};if(r!=AVERROR(EAGAIN))ck(r);if(drained)return {};int n=av_read_frame(fmt,packet);if(n<0){ck(avcodec_send_packet(dec,nullptr));drained=true;}else if(packet->stream_index==stream)ck(avcodec_send_packet(dec,packet));av_packet_unref(packet);}}
 void seek(int64_t pts){ck(av_seek_frame(fmt,stream,pts,AVSEEK_FLAG_BACKWARD));avcodec_flush_buffers(dec);drained=false;}
 Frame at(int64_t pts){seek(pts);Frame x;while((x=next()))if(x->pts>=pts)return x;return {};}
};
static std::vector<uint8_t> bgra(Frame x){AVFrame *s=av_frame_alloc();const AVFrame *f=x->frame;if(f->format==AV_PIX_FMT_VIDEOTOOLBOX){ck(av_hwframe_transfer_data(s,f,0));f=s;}std::vector<uint8_t> b(f->width*f->height*4);uint8_t *d[]={b.data(),0,0,0};int st[]={f->width*4,0,0,0};auto sw=sws_getContext(f->width,f->height,(AVPixelFormat)f->format,f->width,f->height,AV_PIX_FMT_BGRA,SWS_BILINEAR,0,0,0);sws_scale(sw,f->data,f->linesize,0,f->height,d,st);sws_freeContext(sw);av_frame_free(&s);return b;}
struct State {int rotation=0;bool camera=false,creative=false,compare=false;};
struct Authority {const Frame source;const uint64_t generation,serial;const State state;const id<MTLTexture> texture;Authority(Frame f,uint64_t g,uint64_t s,State c,id<MTLTexture> t):source(f),generation(g),serial(s),state(c),texture(t){} };
static NSString *shader=@"#include <metal_stdlib>\nusing namespace metal;struct P{uint w,h,rot,cam,creative,compare,nv12;};\n"
"float3 cube(float3 x,device const float4*v,float lo,float hi){float3 p=clamp((x-lo)/(hi-lo),0.f,1.f),z=0;for(uint b=0;b<2;b++)for(uint g=0;g<2;g++)for(uint r=0;r<2;r++)z+=v[r+2*g+4*b].xyz*(r?p.x:1-p.x)*(g?p.y:1-p.y)*(b?p.z:1-p.z);return z;}\n"
"kernel void process(texture2d<float,access::read>a[[texture(0)]],texture2d<float,access::read>uv[[texture(1)]],texture2d<float,access::write>o[[texture(2)]],device const float4*cam[[buffer(0)]],device const float4*cr[[buffer(1)]],constant P&p[[buffer(2)]],uint2 q[[thread_position_in_grid]]){if(q.x>=p.w||q.y>=p.h)return;float2 s=(float2(q)+.5)/float2(p.w,p.h);if(p.rot==1)s=float2(s.y,1-s.x);if(p.rot==2)s=1-s;if(p.rot==3)s=float2(1-s.y,s.x);uint2 t=min(uint2(s*float2(a.get_width(),a.get_height())),uint2(a.get_width()-1,a.get_height()-1));float3 rgb=a.read(t).rgb;if(p.nv12){float y=(a.read(t).r*255-16)/219;float2 c=(uv.read(t/2).rg*255-128)/224;rgb=float3(y+1.402*c.y,y-.344136*c.x-.714136*c.y,y+1.772*c.x);rgb=clamp(rgb,0.f,1.f);}if(!p.compare){if(p.cam)rgb=cube(rgb,cam,.1,.9);if(p.creative)rgb=cube(rgb,cr,0,1);}o.write(float4(clamp(rgb,0.f,1.f),1),q);}\n"
"struct V{float4 p[[position]];float2 uv;};vertex V vs(uint i[[vertex_id]]){float2 p[3]={float2(-1,-1),float2(3,-1),float2(-1,3)};V o;o.p=float4(p[i],0,1);o.uv=float2((p[i].x+1)/2,1-(p[i].y+1)/2);return o;}fragment float4 fs(V v[[stage_in]],texture2d<float>t[[texture(0)]]){constexpr sampler s(filter::nearest);return t.sample(s,v.uv);}";
struct Params{uint32_t w,h,rot,cam,creative,compare,nv12;};
class Renderer {
public:NSString *asset=@"unset";id<MTLDevice> dev,consumer;id<MTLCommandQueue> prodQueue,uiQueue;id<MTLSharedEvent> ready,released;id<MTLComputePipelineState> pipeline;id<MTLRenderPipelineState> display;id<MTLBuffer> cam,cr;NSWindow *window;NSView *view;CAMetalLayer *layer;CVMetalTextureCacheRef cache=nullptr;uint64_t generation=1,serial=0,surfaceGeneration=0;std::shared_ptr<const Authority> retained;double gpu=0,copy=0,ackDelay=0;bool acked=false;int maxError=0;
 IOSurfaceRef surface=nullptr;id<MTLTexture> output,imported;int ow=0,oh=0;IOSurfaceRef surfaces[3]={};id<MTLTexture> outputs[3],imports[3];int widths[3]={},heights[3]={};std::weak_ptr<const Authority> owners[3];int selected=0;float cameras[32],creatives[32];
 Renderer(){dev=MTLCreateSystemDefaultDevice();consumer=MTLCreateSystemDefaultDevice();prodQueue=[dev newCommandQueue];uiQueue=[consumer newCommandQueue];ready=[dev newSharedEvent];released=[consumer newSharedEvent];NSError *err=nil;MTLCompileOptions *options=[MTLCompileOptions new];options.fastMathEnabled=NO;auto lib=[dev newLibraryWithSource:shader options:options error:&err];if(!lib){fprintf(stderr,"%s\n",err.description.UTF8String);exit(4);}pipeline=[dev newComputePipelineStateWithFunction:[lib newFunctionWithName:@"process"] error:&err];MTLRenderPipelineDescriptor *rp=[MTLRenderPipelineDescriptor new];rp.vertexFunction=[lib newFunctionWithName:@"vs"];rp.fragmentFunction=[lib newFunctionWithName:@"fs"];rp.colorAttachments[0].pixelFormat=MTLPixelFormatBGRA8Unorm;display=[dev newRenderPipelineStateWithDescriptor:rp error:&err];for(int b=0;b<2;b++)for(int g=0;g<2;g++)for(int r=0;r<2;r++){int i=(r+2*g+4*b)*4;cameras[i]=r*.7+.05+.1*g*b;cameras[i+1]=g*.6+.1+.1*r*b;cameras[i+2]=b*.5+.15+.1*r*g;cameras[i+3]=1;creatives[i]=1-r*.8+.05*g*b;creatives[i+1]=g*.9+.05*r*b;creatives[i+2]=b*.8+.08*r*g;creatives[i+3]=1;}cam=[dev newBufferWithBytes:cameras length:sizeof(cameras) options:MTLResourceStorageModeShared];cr=[dev newBufferWithBytes:creatives length:sizeof(creatives) options:MTLResourceStorageModeShared];CVMetalTextureCacheCreate(NULL,NULL,dev,NULL,&cache);open();}
 void open(){window=[[NSWindow alloc]initWithContentRect:NSMakeRect(80,80,480,270) styleMask:NSWindowStyleMaskTitled|NSWindowStyleMaskResizable|NSWindowStyleMaskClosable backing:NSBackingStoreBuffered defer:NO];window.releasedWhenClosed=NO;window.title=@"Lightflow G1b proof — task-local, muted";window.collectionBehavior=NSWindowCollectionBehaviorFullScreenPrimary;view=[[NSView alloc]initWithFrame:NSMakeRect(0,0,480,270)];view.wantsLayer=YES;layer=[CAMetalLayer layer];layer.device=consumer;layer.pixelFormat=MTLPixelFormatBGRA8Unorm;layer.framebufferOnly=YES;layer.contentsScale=window.backingScaleFactor;layer.drawableSize=CGSizeMake(480*layer.contentsScale,270*layer.contentsScale);view.layer=layer;window.contentView=view;[window orderFront:nil];pump(.1);}
 ~Renderer(){[window close];if(cache)CFRelease(cache);for(int i=0;i<3;i++)if(surfaces[i])CFRelease(surfaces[i]);}
 void size(int w,int h){int slot=-1;for(int i=0;i<3;i++){int n=(serial+i)%3;if(owners[n].expired()){slot=n;break;}}if(slot<0){emit(@{@"fault":@"surface-backpressure",@"slots":@3});exit(13);}selected=slot;if(w==widths[slot]&&h==heights[slot]){surface=surfaces[slot];output=outputs[slot];imported=imports[slot];ow=w;oh=h;return;}if(surfaces[slot])CFRelease(surfaces[slot]);NSDictionary *p=@{(__bridge NSString*)kIOSurfaceWidth:@(w),(__bridge NSString*)kIOSurfaceHeight:@(h),(__bridge NSString*)kIOSurfaceBytesPerElement:@4,(__bridge NSString*)kIOSurfaceBytesPerRow:@(IOSurfaceAlignProperty(kIOSurfaceBytesPerRow,w*4)),(__bridge NSString*)kIOSurfacePixelFormat:@((uint32_t)'BGRA')};surface=IOSurfaceCreate((__bridge CFDictionaryRef)p);auto d=[MTLTextureDescriptor texture2DDescriptorWithPixelFormat:MTLPixelFormatBGRA8Unorm width:w height:h mipmapped:NO];d.usage=MTLTextureUsageShaderRead|MTLTextureUsageShaderWrite;d.storageMode=MTLStorageModeShared;output=[dev newTextureWithDescriptor:d iosurface:surface plane:0];imported=[consumer newTextureWithDescriptor:d iosurface:surface plane:0];if(!output||!imported)exit(5);ow=w;oh=h;surfaces[slot]=surface;outputs[slot]=output;imports[slot]=imported;widths[slot]=w;heights[slot]=h;surfaceGeneration++;}
 static void cubeCPU(float *x,float *table,float lo,float hi){float p[3],z[3]={};for(int c=0;c<3;c++)p[c]=fmaxf(0,fminf(1,(x[c]-lo)/(hi-lo)));for(int b=0;b<2;b++)for(int g=0;g<2;g++)for(int r=0;r<2;r++){float v=(r?p[0]:1-p[0])*(g?p[1]:1-p[1])*(b?p[2]:1-p[2]);for(int c=0;c<3;c++)z[c]+=table[(r+2*g+4*b)*4+c]*v;}memcpy(x,z,sizeof(z));}
 NSDictionary *present(Frame f,State s,NSString *action,bool capture,bool stale=false,bool cpuCopy=false){int rot=(f? s.rotation:0)%4;++serial;size(rot%2?f->frame->height:f->frame->width,rot%2?f->frame->width:f->frame->height);auto a=std::make_shared<const Authority>(f,generation,serial,s,output);owners[selected]=a;id<MTLTexture> source,chroma;CVMetalTextureRef y=nullptr,uv=nullptr;std::vector<uint8_t> raw;bool hw=f->frame->format==AV_PIX_FMT_VIDEOTOOLBOX;
 if(hw){auto pb=(CVPixelBufferRef)f->frame->data[3];if(CVPixelBufferGetPixelFormatType(pb)!=kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange)exit(9);CVMetalTextureCacheCreateTextureFromImage(NULL,cache,pb,NULL,MTLPixelFormatR8Unorm,f->frame->width,f->frame->height,0,&y);CVMetalTextureCacheCreateTextureFromImage(NULL,cache,pb,NULL,MTLPixelFormatRG8Unorm,f->frame->width/2,f->frame->height/2,1,&uv);source=CVMetalTextureGetTexture(y);chroma=CVMetalTextureGetTexture(uv);}else{raw=bgra(f);auto d=[MTLTextureDescriptor texture2DDescriptorWithPixelFormat:MTLPixelFormatBGRA8Unorm width:f->frame->width height:f->frame->height mipmapped:NO];d.usage=MTLTextureUsageShaderRead;source=[dev newTextureWithDescriptor:d];[source replaceRegion:MTLRegionMake2D(0,0,f->frame->width,f->frame->height) mipmapLevel:0 withBytes:raw.data() bytesPerRow:f->frame->width*4];chroma=source;}
 auto cmd=[prodQueue commandBuffer];if(serial>1)[cmd encodeWaitForEvent:released value:serial-1];auto e=[cmd computeCommandEncoder];Params p={(uint32_t)ow,(uint32_t)oh,(uint32_t)rot,(uint32_t)s.camera,(uint32_t)s.creative,(uint32_t)s.compare,(uint32_t)hw};[e setComputePipelineState:pipeline];[e setTexture:source atIndex:0];[e setTexture:chroma atIndex:1];[e setTexture:output atIndex:2];[e setBuffer:cam offset:0 atIndex:0];[e setBuffer:cr offset:0 atIndex:1];[e setBytes:&p length:sizeof(p) atIndex:2];[e dispatchThreads:MTLSizeMake(ow,oh,1) threadsPerThreadgroup:MTLSizeMake(16,16,1)];[e endEncoding];[cmd encodeSignalEvent:ready value:serial];[cmd commit];[cmd waitUntilCompleted];gpu=cmd.GPUEndTime-cmd.GPUStartTime;bool completed=cmd.status==MTLCommandBufferStatusCompleted;
 if(stale){generation++;released.signaledValue=serial;if(y)CFRelease(y);if(uv)CFRelease(uv);return @{ @"action":action,@"stale_rejected":@YES,@"published":@NO,@"generation":@(generation)};}
 uint64_t pixelHash=0;maxError=0;copy=0;double t=now();std::vector<uint8_t> pixels;if(capture||cpuCopy){pixels.resize(ow*oh*4);[output getBytes:pixels.data() bytesPerRow:ow*4 fromRegion:MTLRegionMake2D(0,0,ow,oh) mipmapLevel:0];if(cpuCopy){auto fallback=[MTLTextureDescriptor texture2DDescriptorWithPixelFormat:MTLPixelFormatBGRA8Unorm width:ow height:oh mipmapped:NO];fallback.usage=MTLTextureUsageShaderRead;imported=[consumer newTextureWithDescriptor:fallback];[imported replaceRegion:MTLRegionMake2D(0,0,ow,oh) mipmapLevel:0 withBytes:pixels.data() bytesPerRow:ow*4];}copy=now()-t;pixelHash=capture?hash(pixels.data(),pixels.size()):0;}
 if(capture){if(hw)raw=bgra(f);for(int yy=0;yy<oh;yy++)for(int xx=0;xx<ow;xx++){float u=(xx+.5f)/ow,v=(yy+.5f)/oh,ss=u,tt=v;if(rot==1){ss=v;tt=1-u;}if(rot==2){ss=1-u;tt=1-v;}if(rot==3){ss=1-v;tt=u;}int i=((int)(tt*f->frame->height)*f->frame->width+(int)(ss*f->frame->width))*4;float rgb[]={raw[i+2]/255.f,raw[i+1]/255.f,raw[i]/255.f};if(!s.compare){if(s.camera)cubeCPU(rgb,cameras,.1,.9);if(s.creative)cubeCPU(rgb,creatives,0,1);}for(int c=0;c<3;c++)maxError=std::max(maxError,abs((int)lroundf(fmaxf(0,fminf(1,rgb[c]))*255)-pixels[(yy*ow+xx)*4+2-c]));}}
 auto d=[layer nextDrawable];if(!d)exit(6);auto c=[uiQueue commandBuffer];[c encodeWaitForEvent:ready value:serial];MTLRenderPassDescriptor *pass=[MTLRenderPassDescriptor renderPassDescriptor];pass.colorAttachments[0].texture=d.texture;pass.colorAttachments[0].loadAction=MTLLoadActionClear;pass.colorAttachments[0].storeAction=MTLStoreActionStore;auto re=[c renderCommandEncoderWithDescriptor:pass];[re setRenderPipelineState:display];[re setFragmentTexture:imported atIndex:0];[re drawPrimitives:MTLPrimitiveTypeTriangle vertexStart:0 vertexCount:3];[re endEncoding];[c encodeSignalEvent:released value:serial];auto ack=std::make_shared<std::atomic<bool>>(false);auto stamp=std::make_shared<std::atomic<double>>(0);[d addPresentedHandler:^(id<MTLDrawable> dr){stamp->store(dr.presentedTime);ack->store(true,std::memory_order_release);}];t=now();[c presentDrawable:d];[c commit];[c waitUntilCompleted];double timeout=now()+1;while(!ack->load(std::memory_order_acquire)&&now()<timeout)pump(.001);double displayTime=stamp->load();acked=ack->load()&&displayTime>0;ackDelay=now()-t;if(acked&&generation==a->generation)retained=a;if(y)CFRelease(y);if(uv)CFRelease(uv);
 NSDictionary *record=@{@"action":action,@"session":asset,@"generation":@(a->generation),@"serial":@(a->serial),@"pts":@(f->pts),@"tb_num":@(f->tb.num),@"tb_den":@(f->tb.den),@"decoded_sequence":@(f->sequence),@"source_clockwise_quarters":@(s.rotation),@"camera":@(s.camera),@"camera_table_hash":hs(hash((uint8_t*)cameras,sizeof(cameras))),@"creative_table_hash":hs(hash((uint8_t*)creatives,sizeof(creatives))),@"creative":@(s.creative),@"compare":@(s.compare),@"source_pixels":hs(hw?0:hash(raw.data(),raw.size())),@"capture_pixels":hs(pixelHash),@"capture_serial":@(capture&&acked?a->serial:0),@"surface_id":@(IOSurfaceGetID(surface)),@"surface_generation":@(surfaceGeneration),@"producer_completed":@(completed),@"consumer_completed":@(c.status==MTLCommandBufferStatusCompleted),@"presented_ack":@(acked),@"presented_time":@(displayTime),@"published_serial":@(retained?retained->serial:0),@"gpu_ms":@(gpu*1000),@"cpu_copy_ms":@(copy*1000),@"ack_ms":@(ackDelay*1000),@"cpu_oracle_max_channel_error":@(maxError),@"rss":@(rss()),@"hardware_frame":@(hw)};return record;
 }
};
// Pitch-preserving FFmpeg atempo output: source clock maps processed output samples * speed.
static std::vector<float> tempo(const std::vector<float>& pcm,double speed){if(speed==1)return pcm;AVFilterGraph *g=avfilter_graph_alloc();AVFilterContext *src,*sink;ck(avfilter_graph_create_filter(&src,avfilter_get_by_name("abuffer"),"src","time_base=1/48000:sample_rate=48000:sample_fmt=flt:channel_layout=mono",0,g));ck(avfilter_graph_create_filter(&sink,avfilter_get_by_name("abuffersink"),"sink",0,0,g));std::string filters;double r=speed;while(r<.5){filters+="atempo=0.5,";r/=.5;}while(r>2){filters+="atempo=2,";r/=2;}filters+="atempo="+std::to_string(r);AVFilterInOut *in=avfilter_inout_alloc(),*out=avfilter_inout_alloc();out->name=av_strdup("in");out->filter_ctx=src;out->pad_idx=0;in->name=av_strdup("out");in->filter_ctx=sink;in->pad_idx=0;ck(avfilter_graph_parse_ptr(g,filters.c_str(),&in,&out,0));ck(avfilter_graph_config(g,0));avfilter_inout_free(&in);avfilter_inout_free(&out);AVFrame *f=av_frame_alloc(),*o=av_frame_alloc();std::vector<float> result;for(size_t i=0;i<pcm.size();i+=1024){av_frame_unref(f);f->format=AV_SAMPLE_FMT_FLT;f->sample_rate=48000;av_channel_layout_default(&f->ch_layout,1);f->nb_samples=std::min((size_t)1024,pcm.size()-i);f->pts=i;ck(av_frame_get_buffer(f,0));memcpy(f->data[0],pcm.data()+i,f->nb_samples*4);ck(av_buffersrc_add_frame(src,f));while(av_buffersink_get_frame(sink,o)==0){result.insert(result.end(),(float*)o->data[0],(float*)o->data[0]+o->nb_samples);av_frame_unref(o);}}ck(av_buffersrc_add_frame(src,nullptr));while(av_buffersink_get_frame(sink,o)==0){result.insert(result.end(),(float*)o->data[0],(float*)o->data[0]+o->nb_samples);av_frame_unref(o);}av_frame_free(&f);av_frame_free(&o);avfilter_graph_free(&g);return result;}
class Audio {
public:std::vector<float> original,processed;AudioQueueRef q=nullptr;size_t offset=0;std::atomic<uint64_t> filled{0},callbacks{0};double origin=0,speed=1;uint64_t restart=0;bool running=false;
 Audio(const char *path){NSData*d=[NSData dataWithContentsOfFile:@(path)];original.assign((float*)d.bytes,(float*)d.bytes+d.length/4);if(original.empty())exit(10);}
 static void fill(void *u,AudioQueueRef q,AudioQueueBufferRef b){auto a=(Audio*)u;size_t samples=b->mAudioDataBytesCapacity/4;auto p=(float*)b->mAudioData;for(size_t i=0;i<samples;i++){p[i]=a->processed[a->offset++];if(a->offset==a->processed.size())a->offset=0;}b->mAudioDataByteSize=samples*4;AudioQueueEnqueueBuffer(q,b,0,0);a->filled+=samples;a->callbacks++;}
 void start(double seek,double rate){stop();speed=rate;origin=seek;processed=tempo(original,rate);offset=std::min(processed.size()-1,(size_t)(seek/rate*48000));filled=0;callbacks=0;AudioStreamBasicDescription f={};f.mSampleRate=48000;f.mFormatID=kAudioFormatLinearPCM;f.mFormatFlags=kAudioFormatFlagIsFloat|kAudioFormatFlagIsPacked;f.mBytesPerPacket=f.mBytesPerFrame=4;f.mFramesPerPacket=1;f.mChannelsPerFrame=1;f.mBitsPerChannel=32;aqck(AudioQueueNewOutput(&f,fill,this,NULL,NULL,0,&q));aqck(AudioQueueSetParameter(q,kAudioQueueParam_Volume,0));for(int i=0;i<3;i++){AudioQueueBufferRef b;aqck(AudioQueueAllocateBuffer(q,1024*4,&b));fill(this,q,b);}aqck(AudioQueueStart(q,NULL));running=true;restart++;}
 double clock(){AudioTimeStamp t={};Boolean discontinuity=false;OSStatus n=AudioQueueGetCurrentTime(q,NULL,&t,&discontinuity);if(n||!(t.mFlags&kAudioTimeStampSampleTimeValid))return -1;return origin+t.mSampleTime/48000*speed;}
 void pause(){aqck(AudioQueuePause(q));running=false;}void resume(){aqck(AudioQueueStart(q,NULL));running=true;}void stop(){if(q){AudioQueueStop(q,true);AudioQueueDispose(q,true);q=nullptr;running=false;}}~Audio(){stop();}
};
static void semantic(const char *path,Renderer &r){Decoder d(path,false);Frame f=d.next();State s;s.rotation=d.rotation;auto first=r.present(f,s,@"paused",true);emit(first);if(!r.acked)emit(r.present(f,s,@"paused-retry",true));emit(r.present(d.next(),s,@"forward",true));emit(r.present(f,s,@"reverse",true));f=d.at(av_rescale_q(2,(AVRational){1,1},d.tb));emit(r.present(f,s,@"seek",true));for(int rot=0;rot<4;rot++)for(int color=0;color<5;color++){s.rotation=(d.rotation+rot)%4;s.camera=color==1||color>=3;s.creative=color==2||color>=3;s.compare=color==4;emit(r.present(f,s,@"rotation-color-capture",true));}
 auto before=r.retained;emit(r.present(f,s,@"cancelled-seek-stale-generation",true,true));bool same=r.retained==before;emit(@{@"action":@"stale-invariant",@"retained_unchanged":@(same),@"capture_pts":@(before->source->pts),@"serial":@(before->serial)});emit(r.present(f,s,@"after-cancel",true));
 // Shared authoring consumers use the acknowledged frame, never clock arithmetic.
 auto a=r.retained;Frame next=d.next();emit(@{@"action":@"authored-boundaries",@"in_pts":@(a->source->pts),@"marker_pts":@(a->source->pts),@"subclip_in_pts":@(a->source->pts),@"inclusive_out_pts":@(a->source->pts),@"exclusive_out_next_pts":@(next->pts),@"timebase_den":@(a->source->tb.den),@"consumer_serial":@(a->serial),@"scope":@"contract adapter proof; production workflows not migrated"});
}
static void reverse(const char *path){Decoder d(path,false);struct O{int64_t pts;uint64_t hash;};std::vector<O> oracle;Frame f;while((f=d.next())){auto b=bgra(f);oracle.push_back({f->pts,hash(b.data(),b.size())});emit(@{@"phase":@"linear-oracle",@"index":@(oracle.size()-1),@"pts":@(f->pts),@"hash":hs(oracle.back().hash)});}emit(@{@"phase":@"oracle",@"frames":@(oracle.size()),@"duration":@(d.duration),@"rss":@(rss())});std::deque<Frame> cache;uint64_t bytes=0;const uint64_t bound=16*1024*1024;uint64_t hits=0,misses=0,maxBytes=0;std::vector<int> starts={(int)oracle.size()-3,(int)oracle.size()/2,300};for(int start:starts)for(int j=0;j<100;j++){int target=start-j;if(target<1)continue;auto want=oracle[target];Frame got;double t=now();uint64_t reads=d.framesRead;bool hit=false;for(auto x:cache)if(x->pts==want.pts){got=x;hit=true;break;}if(!got){misses++;int64_t earlier=std::max((int64_t)0,want.pts-av_rescale_q(8,(AVRational){1,1},d.tb));d.seek(earlier);cache.clear();bytes=0;while((f=d.next())){cache.push_back(f);bytes+=d.w*d.h*4;while(bytes>bound){cache.pop_front();bytes-=d.w*d.h*4;}maxBytes=std::max(maxBytes,bytes);if(f->pts==want.pts){got=f;break;}if(f->pts>want.pts)break;}}else hits++;if(!got)exit(11);auto b=bgra(got);auto h=hash(b.data(),b.size());emit(@{@"phase":@"reverse",@"index":@(target),@"pts":@(got->pts),@"expected_pts":@(want.pts),@"hash":hs(h),@"expected_hash":hs(want.hash),@"exact":@(got->pts==want.pts&&h==want.hash),@"cache_hit":@(hit),@"cache_bytes_upper_bound":@(bytes),@"decoded":@(d.framesRead-reads),@"ms":@((now()-t)*1000),@"rss":@(rss())});if(got->pts!=want.pts||h!=want.hash)exit(12);}
 emit(@{@"phase":@"cache-summary",@"hits":@(hits),@"misses":@(misses),@"byte_bound":@(bound),@"max_accounted_bytes":@(maxBytes),@"scope":@"software frame refs; conservative BGRA byte accounting"});
 d.seek(oracle[250].pts);f=d.next();while(f&&f->pts<oracle[250].pts)f=d.next();Frame n=d.next();emit(@{@"phase":@"forward-after-reverse",@"exact":@(n&&n->pts==oracle[251].pts),@"pts":@(n?n->pts:-1)});
}
static void playback(const char *path,const char *pcm,Renderer &r,double seconds,double speed,bool hw,bool color,bool copy){Decoder d(path,hw);Audio audio(pcm);State s;s.rotation=d.rotation;s.camera=s.creative=color;Frame current=d.next(),future=d.next();audio.start(0,speed);double begin=now(),wall=begin,firstClock=-1,firstWall=0;uint64_t cycle=0,presented=UINT64_MAX,dropped=0;while(now()-begin<seconds){@autoreleasepool{double c=audio.clock();if(c<0){pump(.001);continue;}double target=c+(1.0/60)*speed;if(target>=d.duration){audio.start(0,speed);firstClock=-1;r.generation++;cycle++;d.seek(0);current=d.next();future=d.next();continue;}if(firstClock<0){firstClock=c;firstWall=now();}int skipped=0;while(future&&future->pts*av_q2d(d.tb)<=target){current=future;future=d.next();skipped++;}if(current&&current->sequence!=presented){double decodeDone=now();auto record=r.present(current,s,@"playback",d.w<=320,false,copy);double after=audio.clock();auto row=[record mutableCopy];row[@"audio_source_seconds"]=@(after);row[@"av_offset_ms"]=@((current->pts*av_q2d(d.tb)-after)*1000);row[@"clock_vs_wall_ms"]=@((c-firstClock-(now()-firstWall)*speed)*1000);row[@"wall_elapsed"]=@(now()-begin);row[@"dropped_before_present"]=@(std::max(0,skipped-1));row[@"loop_cycle"]=@(cycle);row[@"speed"]=@(speed);row[@"decode_batch_ms"]=@((decodeDone-wall)*1000);row[@"audio_callbacks"]=@(audio.callbacks.load());row[@"audio_enqueued_samples"]=@(audio.filled.load());emit(row);presented=current->sequence;dropped+=std::max(0,skipped-1);wall=now();}else pump(.001);}}
 audio.pause();double paused=audio.clock();pump(.15);emit(@{@"action":@"audio-pause",@"clock_delta":@(audio.clock()-paused),@"retained_serial":@(r.retained?r.retained->serial:0),@"running":@(audio.running)});audio.resume();pump(.15);emit(@{@"action":@"audio-resume",@"clock_advanced":@(audio.clock()>paused)});audio.stop();r.generation++;current=d.at(av_rescale_q(1,(AVRational){1,1},d.tb));emit(r.present(current,s,@"seek-silent-step",true));audio.start(1,speed);pump(.15);emit(@{@"action":@"seek-resume-clock",@"source_clock":@(audio.clock()),@"origin":@1,@"restart_count":@(audio.restart),@"output_muted":@YES});audio.stop();emit(@{@"action":@"playback-summary",@"seconds":@(seconds),@"speed":@(speed),@"hw":@(hw),@"color":@(color),@"cpu_copy":@(copy),@"dropped":@(dropped),@"rss":@(rss())});}
static void lifecycle(Renderer&r,const char *path){Decoder d(path,false);Frame f=d.next();State s;emit(r.present(f,s,@"shown-open",true));[r.window setContentSize:NSMakeSize(640,360)];r.layer.drawableSize=CGSizeMake(640*r.window.backingScaleFactor,360*r.window.backingScaleFactor);pump(.15);emit(@{@"action":@"resize-retina",@"visible":@(r.window.visible),@"scale":@(r.window.backingScaleFactor),@"drawable_width":@(r.layer.drawableSize.width)});emit(r.present(f,s,@"resized",true));[r.window toggleFullScreen:nil];pump(1.5);emit(@{@"action":@"fullscreen-enter",@"fullscreen_style":@((r.window.styleMask&NSWindowStyleMaskFullScreen)!=0),@"visible":@(r.window.visible)});emit(r.present(f,s,@"fullscreen-present",true));[r.window toggleFullScreen:nil];pump(1.5);emit(@{@"action":@"fullscreen-exit",@"fullscreen_style":@((r.window.styleMask&NSWindowStyleMaskFullScreen)!=0)});for(int i=0;i<4;i++){[r.window close];pump(.05);r.open();emit(r.present(f,s,@"reopen-host",true));}emit(@{@"action":@"activation-state",@"active":@(NSApp.active),@"scope":@"activation transitions not induced; no physical sleep/device switch"});}
int main(int argc,char**argv){setbuf(stdout,NULL);@autoreleasepool{if(argc<3)return 1;fprintf(stderr,"FFmpeg=%s license=%s config=%s\n",av_version_info(),avcodec_license(),avcodec_configuration());[NSApplication sharedApplication];[NSApp setActivationPolicy:NSApplicationActivationPolicyAccessory];NSString *mode=@(argv[1]);if([mode isEqual:@"reverse"]){reverse(argv[2]);return 0;}Renderer r;r.asset=@(argv[2]);emit(@{@"phase":@"interop",@"producer_device":@(r.dev.registryID),@"consumer_device":@(r.consumer.registryID),@"primitive":@"IOSurfaceRef BGRA8 + MTLSharedEvent timeline",@"surface_slots":@3});if([mode isEqual:@"semantic"])semantic(argv[2],r);else if([mode isEqual:@"lifecycle"])lifecycle(r,argv[2]);else if([mode isEqual:@"play"]&&argc>=9)playback(argv[2],argv[3],r,atof(argv[4]),atof(argv[5]),atoi(argv[6]),atoi(argv[7]),atoi(argv[8]));else return 1;[r.window close];pump(.05);}return 0;}
