#include <AudioToolbox/AudioToolbox.h>
#include <stdatomic.h>
#include <math.h>
#include <stdio.h>
#include <unistd.h>
#include <time.h>
#include <stdlib.h>
#include <string.h>
static atomic_uint callbacks=0,refills=0;static atomic_int active=1,refillError=0;static unsigned long phase=0;static int channels=2,frames=4800,service=0;static float amplitude=.08f;static AudioQueueBufferRef buffers[3];static atomic_int ready[3];
static double now(void){struct timespec t;clock_gettime(CLOCK_MONOTONIC,&t);return t.tv_sec+t.tv_nsec/1e9;}
static void fill(AudioQueueBufferRef b){float*p=b->mAudioData;for(int i=0;i<frames;i++,phase++){float v=amplitude*sin(2*M_PI*440*phase/48000.);for(int c=0;c<channels;c++)p[channels*i+c]=v;}b->mAudioDataByteSize=frames*channels*4;}
static void callback(void*u,AudioQueueRef q,AudioQueueBufferRef b){atomic_fetch_add(&callbacks,1);if(service){for(int i=0;i<3;i++)if(buffers[i]==b)atomic_store(&ready[i],1);return;}if(atomic_load(&active)){fill(b);OSStatus s=AudioQueueEnqueueBuffer(q,b,0,NULL);if(s)atomic_store(&refillError,s);else atomic_fetch_add(&refills,1);}}
static void status(const char*n,OSStatus s){printf("{\"api\":\"%s\",\"status\":%d}\n",n,(int)s);fflush(stdout);}
int main(int argc,char**argv){channels=argc>1?atoi(argv[1]):2;frames=argc>2?atoi(argv[2]):4800;service=argc>3?atoi(argv[3]):0;if(argc>4)amplitude=0;setbuf(stdout,NULL);AudioStreamBasicDescription f={.mSampleRate=48000,.mFormatID=kAudioFormatLinearPCM,.mFormatFlags=kAudioFormatFlagIsFloat|kAudioFormatFlagIsPacked,.mBytesPerPacket=channels*4,.mFramesPerPacket=1,.mBytesPerFrame=channels*4,.mChannelsPerFrame=channels,.mBitsPerChannel=32};printf("{\"asbd\":{\"rate\":48000,\"format\":\"lpcm\",\"flags\":9,\"bytesPacket\":%d,\"framesPacket\":1,\"bytesFrame\":%d,\"channels\":%d,\"bits\":32},\"framesBuffer\":%d,\"bufferCount\":3,\"dispatch\":\"AudioQueue internal thread, NULL runloop\"}\n",channels*4,channels*4,channels,frames);printf("{\"actualChannels\":%d,\"actualFramesBuffer\":%d,\"serviceCallbackModel\":%d,\"silentPCM\":%d}\n",channels,frames,service,amplitude==0);AudioQueueRef q=NULL;OSStatus s=AudioQueueNewOutput(&f,callback,NULL,NULL,NULL,0,&q);status("AudioQueueNewOutput",s);if(s)return 1;for(int i=0;i<3;i++){AudioQueueBufferRef b=NULL;s=AudioQueueAllocateBuffer(q,frames*channels*4,&b);status("AudioQueueAllocateBuffer",s);if(s)goto done;buffers[i]=b;fill(b);s=AudioQueueEnqueueBuffer(q,b,0,NULL);status("AudioQueueEnqueueBuffer",s);if(s)goto done;}double start=now();s=AudioQueueStart(q,NULL);printf("{\"api\":\"AudioQueueStart\",\"status\":%d,\"elapsed\":%.6f}\n",(int)s,now()-start);for(int i=0;i<20;i++){UInt32 running=0,n=4;OSStatus r=AudioQueueGetProperty(q,kAudioQueueProperty_IsRunning,&running,&n);AudioTimeStamp t={0};Boolean disc=0;OSStatus c=AudioQueueGetCurrentTime(q,NULL,&t,&disc);printf("{\"poll\":%d,\"runningStatus\":%d,\"running\":%u,\"timeStatus\":%d,\"sampleTime\":%.3f,\"flags\":%u,\"discontinuity\":%d,\"callbacks\":%u,\"refills\":%u}\n",i,(int)r,running,(int)c,t.mSampleTime,t.mFlags,disc,atomic_load(&callbacks),atomic_load(&refills));for(int tick=0;tick<20;tick++){usleep(5000);if(service)for(int j=0;j<3;j++)if(atomic_exchange(&ready[j],0)){fill(buffers[j]);OSStatus e=AudioQueueEnqueueBuffer(q,buffers[j],0,NULL);if(e)atomic_store(&refillError,e);else atomic_fetch_add(&refills,1);}}if(s)break;}
done:atomic_store(&active,0);status("AudioQueueStop immediate",AudioQueueStop(q,true));status("AudioQueueDispose immediate",AudioQueueDispose(q,true));printf("{\"finalCallbacks\":%u,\"refills\":%u,\"refillError\":%d}\n",atomic_load(&callbacks),atomic_load(&refills),atomic_load(&refillError));return s?1:0;}
