// Bounded derivative: native backend timing and protected current-frame authority.
// backendOnly consumer is a GPU snapshot fixture, never an Avalonia/scanout claim.
#include <sys/resource.h>
static double cpuSeconds(){rusage u={};getrusage(RUSAGE_SELF,&u);return u.ru_utime.tv_sec+u.ru_utime.tv_usec/1e6+u.ru_stime.tv_sec+u.ru_stime.tv_usec/1e6;}
static void measure(const char* path,const char* pcm,double seconds,double rate,bool color,bool transitions,bool faults,bool loops){
 Decoder d(path,true);Audio audio(pcm);Renderer r;r.asset=@(path);State state;state.camera=state.creative=color;
 Frame current=d.next(),future=d.next();double decodeStart=0;audio.start(0,rate);double begin=now(),cpu=cpuSeconds(),origin=0;uint64_t published=UINT64_MAX,draws=0,skippedTotal=0,loop=0;int transition=0;bool injected=false;double queueStart=now();
 emit(@{@"kind":@"environment",@"width":@(d.w),@"height":@(d.h),@"duration":@(d.duration),@"timebase_num":@(d.tb.num),@"timebase_den":@(d.tb.den),@"backend_snapshot_fixture":@(backendOnly),@"audio_gain":@0,@"device":@(r.dev.registryID),@"configuration":@(avcodec_configuration())});
 while(now()-begin<seconds){@autoreleasepool{
 double wall=now()-begin;
 if(transitions&&transition<4&&wall>=(transition+1)*4){double old=rate;double at=audio.clock();double rates[]={2,1,.5,1};rate=rates[transition++];double t=now();r.generation++;audio.start(at,rate);origin=at;emit(@{@"kind":@"speed-transition",@"from":@(old),@"to":@(rate),@"source_origin":@(at),@"generation":@(r.generation),@"restart_ms":@((now()-t)*1000),@"wall":@(wall),@"scope":@"actual live queue restart; predecoded atempo input, not seamless streaming"});}
 if(faults&&!injected&&wall>2){injected=true;double before=audio.clock();audio.pause();double t=now();std::this_thread::sleep_for(std::chrono::milliseconds(120));double after=audio.clock();audio.resume();emit(@{@"kind":@"rapid-pause-resume",@"clock_delta":@(after-before),@"held_serial":@(r.retained?r.retained->serial:0),@"ms":@((now()-t)*1000)});
 // Withhold AudioQueue refill to establish actual queue depletion and protect/rebase.
 AudioQueueStop(audio.q,true);emit(@{@"kind":@"queue-depletion",@"scope":@"injected queue stop, not callback-detected physical underrun",@"protected_serial":@(r.retained?r.retained->serial:0)});r.generation++;audio.start(before,rate);emit(@{@"kind":@"output-recreated",@"generation":@(r.generation),@"source_origin":@(before),@"restart":@(audio.restart)});
 injectedRenderDelay=.12;emit(@{@"kind":@"render-delay",@"injected_ms":@120,@"protected_serial":@(r.retained?r.retained->serial:0),@"scope":@"producer completion wait deliberately delayed; GPU hardware stall not induced"});std::this_thread::sleep_for(std::chrono::milliseconds(100));emit(@{@"kind":@"decode-starvation",@"injected_ms":@100,@"scope":@"scheduler withholding; decoder/device stall simulated"});
 }
 double clock=audio.clock();if(clock<0){std::this_thread::sleep_for(std::chrono::milliseconds(1));continue;}
 double span=loops?1.0:d.duration-.1;
 if(clock>=span){double t=now();double finalPts=r.retained?r.retained->source->pts*av_q2d(d.tb):-1;r.generation++;loop++;audio.start(0,rate);origin=0;d.seek(0);current=d.next();future=d.next();published=UINT64_MAX;emit(@{@"kind":@"loop-boundary",@"loop":@(loop),@"last_pts_seconds":@(finalPts),@"new_origin":@0,@"generation":@(r.generation),@"restart_ms":@((now()-t)*1000),@"scope":@"explicit queue restart; discontinuity measured, not gapless"});continue;}
 double chooseStart=now();int advanced=0;while(future&&future->pts*av_q2d(d.tb)<=clock){current=future;double t=now();future=d.next();decodeStart=now()-t;advanced++;}
 if(current&&current->sequence!=published){
 double pts=current->pts*av_q2d(d.tb);double t=now();auto record=[r.present(current,state,@"completion-playback",false) mutableCopy];double after=audio.clock();
 record[@"kind"]=@"frame";record[@"wall"]=@(wall);record[@"speed"]=@(rate);record[@"audio_clock_before"]=@(clock);record[@"audio_clock_after"]=@(after);record[@"source_offset_before_ms"]=@((pts-clock)*1000);record[@"source_offset_after_ms"]=@((pts-after)*1000);record[@"wall_offset_after_ms"]=@((pts-after)/rate*1000);record[@"render_ms"]=@((now()-t)*1000);record[@"decode_ms"]=@(decodeStart*1000);record[@"selection_decode_ms"]=@((t-chooseStart)*1000);record[@"queue_depth"]=@(future?1:0);record[@"skipped"]=@(std::max(0,advanced-1));record[@"loop"]=@(loop);record[@"clock_origin"]=@(origin);emit(record);draws++;skippedTotal+=std::max(0,advanced-1);published=current->sequence;
 }else std::this_thread::sleep_for(std::chrono::milliseconds(1));
 if(!backendOnly)pump(.0001);
 }}
 audio.stop();emit(@{@"kind":@"summary",@"seconds":@(now()-begin),@"frames":@(draws),@"decoded":@(d.framesRead),@"skipped":@(skippedTotal),@"loops":@(loop),@"cpu_seconds":@(cpuSeconds()-cpu),@"rss":@(rss()),@"authority_scope":backendOnly?@"backend GPU snapshot only; UI acceptance not executed":@"native drawable fixture; not final Avalonia display"});
}
static void tempoOracle(){
 std::vector<float> input(48000*20);for(int pulse=1;pulse<=4;pulse++)for(int i=0;i<4800;i++){double e=sin(M_PI*i/4800);input[pulse*48000*4+i]=.8*e*sin(2*M_PI*997*i/48000);}
 for(double speed:{.5,1.,2.}){auto out=tempo(input,speed);std::vector<double> peaks;for(int pulse=1;pulse<=4;pulse++){int expected=(pulse*4+.05)*48000/speed;int lo=std::max(0,expected-12000),hi=std::min((int)out.size()-480,expected+12000),best=lo;double value=-1;for(int j=lo;j<hi;j+=24){double energy=0;for(int k=0;k<480;k++)energy+=out[j+k]*out[j+k];if(energy>value){value=energy;best=j;}}peaks.push_back((best+240)/48000.0*speed-(pulse*4+.05));}
 emit(@{@"kind":@"tempo-content-oracle",@"speed":@(speed),@"input_samples":@(input.size()),@"output_samples":@(out.size()),@"peak_source_errors_ms":@[@(peaks[0]*1000),@(peaks[1]*1000),@(peaks[2]*1000),@(peaks[3]*1000)],@"scope":@"native atempo envelope content vs affine source-clock mapping; not physical speaker timing"});}
}
static void queueStarvation(const char*pcm){Audio audio(pcm);audio.start(0,1);std::this_thread::sleep_for(std::chrono::milliseconds(200));double before=audio.clock();auto queued=audio.filled.load();starved=true;std::this_thread::sleep_for(std::chrono::milliseconds(300));double after=audio.clock();UInt32 running=0,n=sizeof(running);auto status=AudioQueueGetProperty(audio.q,kAudioQueueProperty_IsRunning,&running,&n);emit(@{@"kind":@"actual-audio-starvation",@"before":@(before),@"after":@(after),@"enqueued_samples":@(queued),@"withheld_refills":@(missedRefills.load()),@"property_status":@(status),@"is_running":@(running),@"scope":@"real AudioQueue callbacks withheld; output muted; no physical device change"});audio.stop();starved=false;audio.start(before,1);std::this_thread::sleep_for(std::chrono::milliseconds(100));emit(@{@"kind":@"starvation-recovery",@"origin":@(before),@"recovered_clock":@(audio.clock()),@"callbacks":@(audio.callbacks.load()),@"restart":@(audio.restart)});audio.stop();}
int main(int argc,char**argv){setbuf(stdout,NULL);@autoreleasepool{
 if(argc<2)return 1;const char *dataRoot=nullptr;for(int i=1;i+1<argc;i++)if(strcmp(argv[i],"--data-root")==0)dataRoot=argv[i+1];if(!dataRoot||dataRoot[0]!='/'){fprintf(stderr,"Require absolute task-owned --data-root\n");return 64;}if(strcmp(argv[1],"tempo")==0){tempoOracle();return 0;}if(strcmp(argv[1],"starvation")==0&&argc>=3){queueStarvation(argv[2]);return 0;}if(argc<3)return 1;[NSApplication sharedApplication];[NSApp setActivationPolicy:NSApplicationActivationPolicyAccessory];backendOnly=strcmp(argv[1],"native")!=0;

 if(strcmp(argv[1],"render-fault")==0){Renderer r;Decoder d(argv[2],false);State s;Frame f=d.next();emit(r.present(f,s,@"initial-ready",true));auto held=r.retained;std::vector<uint8_t>a(r.ow*r.oh*4);[held->texture getBytes:a.data() bytesPerRow:r.ow*4 fromRegion:MTLRegionMake2D(0,0,r.ow,r.oh) mipmapLevel:0];auto oldHash=hash(a.data(),a.size());injectedRenderDelay=.12;emit(r.present(d.next(),s,@"render-delay",true));[held->texture getBytes:a.data() bytesPerRow:held->texture.width*4 fromRegion:MTLRegionMake2D(0,0,held->texture.width,held->texture.height) mipmapLevel:0];emit(@{@"kind":@"render-delay-invariant",@"held_hash_unchanged":@(hash(a.data(),a.size())==oldHash),@"held_serial":@(held->serial),@"new_serial":@(r.retained->serial),@"scope":@"CPU producer-completion wait injected; actual GPU snapshot/capture; no physical GPU stall"});s.rotation=1;r.generation++;emit(r.present(f,s,@"surface-dimension-replacement",true));return 0;}
 if(strcmp(argv[1],"semantic")==0){Renderer r;r.asset=@(argv[2]);semantic(argv[2],r);return 0;}
 if(argc<10)return 1;measure(argv[2],argv[3],atof(argv[4]),atof(argv[5]),atoi(argv[6]),atoi(argv[7]),atoi(argv[8]),atoi(argv[9]));
 }return 0;}
