$ErrorActionPreference = 'Stop'
$root = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
# Existing setup verifies the pinned archive SHA-256 before extracting the descriptor authority.
& (Join-Path $PSScriptRoot 'Get-Ffmpeg.ps1')
$manifest = Get-Content (Join-Path $root 'dependencies/ffmpeg.json') -Raw | ConvertFrom-Json
$probe = Join-Path $root 'artifacts/ffmpeg/bin/ffprobe.exe'
$version = (& $probe -version | Select-Object -First 1)
if (-not $version.Contains($manifest.version)) { throw 'FFprobe does not match the pinned version.' }
$json = & $probe -v error -show_pixel_formats -of json
if ($LASTEXITCODE) { throw 'Pixel-format descriptor query failed.' }
$formats = ($json | ConvertFrom-Json).pixel_formats
$lines = [Collections.Generic.List[string]]::new()
$lines.Add('// Generated by scripts/Update-PixelFormatFacts.ps1. Do not hand-edit format mappings.')
$lines.Add("// Authority: FFprobe $($manifest.version), -show_pixel_formats; archive SHA-256 $($manifest.sha256).")
$lines.Add('namespace LightflowStudio;')
$lines.Add('internal static partial class FfprobePixelFormats')
$lines.Add('{')
$lines.Add('    internal const string DescriptorVersion = "' + $manifest.version + '";')
$lines.Add('    private static readonly IReadOnlyDictionary<string, PixelFormatFacts> Facts =')
$lines.Add('        new Dictionary<string, PixelFormatFacts>(StringComparer.Ordinal)')
$lines.Add('        {')
foreach ($format in ($formats | Sort-Object name)) {
    if ($format.flags.hwaccel -ne 0 -or $format.flags.palette -ne 0) { continue }
    $depth = 'null'
    $depths = @($format.components | Select-Object -ExpandProperty bit_depth -Unique)
    if ($depths.Count -eq 1 -and $depths[0] -gt 0 -and $depths[0] -le 64 -and
        @($format.components).Count -eq $format.nb_components) { $depth = [string]$depths[0] }
    $chroma = 'null'
    if ($format.nb_components -ge 3 -and $format.flags.rgb -eq 0 -and
        $null -ne $format.log2_chroma_w -and $null -ne $format.log2_chroma_h) {
        $label = switch ("$($format.log2_chroma_w),$($format.log2_chroma_h)") {
            '1,1' { '4:2:0' }; '1,0' { '4:2:2' }; '0,0' { '4:4:4' }
            default { $null }
        }
        if ($null -ne $label) { $chroma = '"' + $label + '"' }
    }
    if ($depth -ne 'null' -or $chroma -ne 'null') {
        $lines.Add('            ["' + $format.name + '"] = new(' + $depth + ', ' + $chroma + '),')
    }
}
$lines.Add('        };')
$lines.Add('}')
[IO.File]::WriteAllText((Join-Path $root 'LightflowStudio/FfprobePixelFormats.Generated.cs'),
    ($lines -join "`n") + "`n", [Text.UTF8Encoding]::new($false))
